# Generated by Django 5.2.5 on 2026-02-15 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('editor', 'Editor'), ('journalist', 'Journalist'), ('publisher', 'Publisher')], default='reader', max_length=20, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
