# Generated by Django 5.2.5 on 2026-02-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_add_publisher_role_and_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/'),
        ),
    ]
