# Generated by Django 5.2.5 on 2026-02-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletters/%Y/%m/'),
        ),
    ]
